export const listoftascs = [
  {
    id: 9999,
    urgency: 1,
    date: "23/4/5",
    incharge: "אביתר",
    phonenumber: "05266336",
    maincategory: "אינסטלציה",
    maincategorid: 1,
    subcategoryid: 1,
    subname: "כיור",
    location: "כיתה5",
    status: 2,
    Repeatedtask: "כל שלושה חודשים",
  },
  {
    id: 9995,
    urgency: 2,
    date: "23/4/5",
    incharge: "אביתר",
    phonenumber: "05266336",
    maincategory: "אינסטלציה",
    maincategorid: 1,
    subcategoryid: 1,
    subname: "אסלה",
    problom: "סתימה",
    location: "כיתה5",
    status: 1,
    Repeatedtask: "כל שלושה חודשים",
  },
  {
    id: 9994,
    urgency: 3,
    date: "23/4/5",
    incharge: "בעז",
    phonenumber: "05266336",
    maincategory: "חשמל",
    maincategorid: 2,
    subcategoryid: 1,
    subname: "נורה",
    location: "כיתה5",
    status: 1,
    Repeatedtask: "כל שלושה חודשים",
  },
];
