export const listoftascs = [
  {
    ticketid: 95953,
    ticketguid: "EE3CEFC1-E4AE-4853-820E-5998082012A0",
    urgencyadmin: "1",
    dateopened: "09/08/2021 01:11:59",
    comments: "",
    closecost: "",
    closedate: "",
    closebyuserid: "",
    senttouserid: "",
    closecommentstouser: "",
    closecomments: "",
    breadcrumb: "מבנה",
    categoryname: "רשת קרועה",
    statusname: "פנייה חדשה",
    firstname: "Evyatar",
    lastname: "Katz",
    roomName: "החדר של סטפן",
    phone: "0524705867",
    locationName: "קומה 2",
    allowAccessToRoom: "True",
    ticketPlanID: "1443",
  },
  {
    ticketid: 95953,
    ticketguid: "EE3CEFC1-E4AE-4853-820E-5998082012A0",
    urgencyadmin: "2",
    dateopened: "09/08/2021 01:11:59",
    comments: "",
    closecost: "",
    closedate: "",
    closebyuserid: "",
    senttouserid: "",
    closecommentstouser: "",
    closecomments: "",
    breadcrumb: "מבנה",
    categoryname: "רשת קרועה",
    statusname: "בטיפול",
    firstname: "Evyatar",
    lastname: "Katz",
    roomName: "החדר של סטפן",
    phone: "0524705867",
    locationName: "קומה 2",
    allowAccessToRoom: "True",
    ticketPlanID: "1445",
  },
];
